name: 'Run Database Migrations'
description: "Run migrations in one of Peachjar's environments."
author: 'Peachjar Engineering'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  awsAccessKeyId:
    required: true
    description: AWS Access Key ID
  awsSecretAccessKey:
    required: true
    description: AWS Secret Access Key
  environment:
    required: true
    description: Environment to run migrations in
  mig_image:
    required: false
    description: Docker image with the migration
  mig_tag:
    required: false
    description: Tag of the Docker image (defaults to gitsha.slice(0, 7))
  mig_secret:
    required: false
    description: Kubernetes secret that will be mounted with the migration container.
  mig_image_2:
    required: false
    description: Docker image with the migration
  mig_tag_2:
    required: false
    description: Tag of the Docker image (defaults to gitsha.slice(0, 7))
  mig_secret_2:
    required: false
    description: Kubernetes secret that will be mounted with the migration container.
  mig_image_3:
    required: false
    description: Docker image with the migration
  mig_tag_3:
    required: false
    description: Tag of the Docker image (defaults to gitsha.slice(0, 7))
  mig_secret_3:
    required: false
    description: Kubernetes secret that will be mounted with the migration container.
